# Generated by Django 3.1.1 on 2025-11-29 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('msgdate', models.DateField(auto_now_add=True)),
                ('isread', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Query',
                'verbose_name_plural': 'Contact Queries',
                'ordering': ['-msgdate'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electronics', 'Electronics'), ('Electric', 'Electric'), ('IT', 'Information Technology')], max_length=30)),
                ('role', models.CharField(default='Student', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadingdate', models.DateField(auto_now_add=True)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electronics', 'Electronics'), ('Electric', 'Electric'), ('IT', 'Information Technology')], max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('notesfile', models.FileField(upload_to='notes/')),
                ('filetype', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('DOC', 'Word Document'), ('TXT', 'Text File'), ('Image', 'Image'), ('ZIP', 'Compressed File')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Accept', 'Accepted'), ('Reject', 'Rejected')], default='pending', max_length=15)),
                ('category', models.CharField(choices=[('Notes', 'Notes'), ('ModelPapers', 'Model Papers'), ('Guidance', 'Career Guidance')], max_length=30)),
                ('downloads', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploadingdate'],
            },
        ),
    ]
